name: Create and publish a Docker image

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: backend/Dockerfile
            image: ghcr.io/fenyadim/film-nest-backend
            path: backend
          - dockerfile: frontend/Dockerfile
            image: ghcr.io/fenyadim/film-nest-frontend
            path: frontend
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4 # Checking out the repo

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
