name: Create and publish a Docker image

on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: backend/Dockerfile
            image: ghcr.io/fenyadim/film-nest-backend
            path: backend
          - dockerfile: frontend/Dockerfile
            image: ghcr.io/fenyadim/film-nest-frontend
            path: frontend
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4 # Checking out the repo

      - name: login to docker hub
        run: echo "${{ secrets.GH_TOKEN }}" | docker login --username fenyadim --password ${{ secrets.GH_TOKEN }} ghcr.io | docker buildx prune

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: latest
          labels: ${{ steps.meta.outputs.labels }}
